feat: files check improvements

diff --git a/.github/workflows/ci-keyboards.yml b/.github/workflows/ci-keyboards.yml
--- a/.github/workflows/ci-keyboards.yml
+++ b/.github/workflows/ci-keyboards.yml
@@ -18,6 +18,8 @@ jobs:
   validate-keyboard:
     runs-on: ubuntu-latest
     container: qmkfm/qmk_cli
+    strategy:
+      fail-fast: false
 
     steps:
     - uses: actions/checkout@v3
@@ -37,21 +39,29 @@ jobs:
       id: file_changes
       uses: tj-actions/changed-files@v35
       with:
-        #files: keyboards/**
+        #Using pipe here to envoid URL encoding: https://github.com/tj-actions/changed-files#known-limitation
         separator: "|"
 
-    - name: Check added files for undesirable objects
+    - name: Check new files
       shell: 'bash {0}'
       run: |
-        IFS=$'|' read -a NEW_FILES <<< "${{ steps.file_changes.outputs.added_files }}"
+        exit_code=0
+
+        IFS=$'|' read -ra NEW_FILES <<< "${{ steps.file_changes.outputs.added_files }}"
            for newfile in "${NEW_FILES[@]}"; do
-             # Not necessarily rejection-worthy
-             #file -b "${newfile}" | grep -qv "text" && echo "::warning file={file}::non-text file detected"
-             git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --numstat ${{ env.GITHUB_REF }} -- "${newfile}" | cut -f1 | grep -q '-' && echo "::warning file=${newfile}::non-text file detected"
-             # ...shout out to hex files
-             [[ "${newfile##*.}" == 'hex' ]] && echo "::warning file={file}::non-text file (hex) detected"
+             # Flag new files outside of keyboards
+             [[ ! "${newfile}" =~ ^keyboards/ ]] && echo "::warning file=${newfile}::Files added outside of the keyboard directory."
+             #TODO: This will print for every added file rather than every added directory, figure out how to condense (probably just "use Python")
+             [[ "${newfile}" =~ /keymaps/ && ! "${newfile}" =~ /(vial|default)/ ]] && echo "::notice file=${newfile}::Keymaps added other than default and vial"
+             # Flag binary files
+             #file -b "${newfile}" | grep -qv "text" && echo "::warning file=${newfile}::non-text file detected"
+             git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --numstat ${{ env.GITHUB_REF }} -- "${newfile}" | cut -f1 | grep -q '-' && exit_code=1 && echo "::error file=${newfile},title=Binary File Detected::Binary files are not permitted."
+             # ...and Intel hex files, which technically aren't binary.
+             [[ "${newfile##*.}" == 'hex' ]] && exit_code=1 && echo "::error file=${newfile},title=Hex File Detected::Precompiled firmware is not permitted."
            done
            unset IFS
+
+         exit $exit_code
 
     - name: Compile and check affected keyboards
       shell: 'bash {0}'
@@ -71,12 +81,13 @@ jobs:
           for KEYMAP in default vial; do
 
             # Lint failures now will become compilation failures after a few upstream changes, so at least flag to try and get the submitter to fix
-            qmk lint -kb ${KB} -km ${KEYMAP} || echo "::notice title=${KB} ${KEYMAP} Lint Check Failed::Please run qmk lint -kb ${KB} -km ${KEYMAP}"
+            qmk lint -kb ${KB} -km ${KEYMAP} || echo "::warning title=Lint Check Failed::Please run qmk lint -kb ${KB} -km ${KEYMAP} and try to correct failures. Lint failures now will become compilation failures in later versions of QMK."
 
             # Ensure keymaps build
             make ${KB}:${KEYMAP} -j $(nproc) -e SILENT=true
-            exit_code=$(( $exit_code | $? ))
+            # If any fail, step has failed.
+            exit_code=$(( $? || exit_code ))
           done
         done
 
-        test $exit_code -eq 0
+        exit $exit_code
